# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Facebook Trial' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Facebook Trial
	pod 'FBSDKCoreKit'
	pod 'FBSDKLoginKit'
        pod 'FBSDKShareKit'

  target 'Facebook TrialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Facebook TrialUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
